name: ci master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: 28f77aaa-53e7-47bc-ad78-d8d7b2b98009
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: b087ec80-bbdd-4b0a-9fb3-ca2eb729208c
      ARM_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47

      TF_VAR_cluster_client_secret: ${{ secrets.NGC_CLUSTER_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v1
    - name: Terraform format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: fmt
        tf_actions_working_dir: '.'
        tf_actions_comment: false
    - name: terraform init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: init
        tf_actions_working_dir: '.'
        tf_actions_comment: false
    - name: terraform validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: validate
        tf_actions_working_dir: '.'
        tf_actions_comment: false
    - name: terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.16
        tf_actions_subcommand: plan
        tf_actions_working_dir: '.'
        tf_actions_comment: false
